/**
 * App-level content and copy.
 * All user-facing strings live here — never inline in components.
 * Structured for future CMS migration.
 */

function ordinal(n: number): string {
  const suffixes = ['th', 'st', 'nd', 'rd'];
  const mod100 = n % 100;
  return `${n}${suffixes[(mod100 - 20) % 10] || suffixes[mod100] || suffixes[0]}`;
}

export const appContent = {
  meta: {
    title: 'Draftr',
    description: 'Ride coordination for cycling clubs',
    shortName: 'Draftr',
  },

  nav: {
    home: 'Home',
    rides: 'Rides',
    notifications: 'Notifications',
    profile: 'Profile',
    manage: 'Manage',
    club: 'Club',
  },

  header: {
    viewAllNotifications: 'View All',
    signOut: 'Sign Out',
    profile: 'Profile',
    profileMenu: 'Profile menu',
    noNotifications: 'No new notifications',
    notificationsBadge: (count: string) => `Notifications, ${count} unread`,
  },

  avatarMenu: {
    myProfile: 'My Profile',
    settings: 'My Settings',
    signOut: 'Sign out',
  },

  auth: {
    signIn: {
      heading: 'Welcome to Draftr',
      subheading: 'Sign in to find your next ride',
      emailLabel: 'Email',
      passwordLabel: 'Password',
      submitButton: 'Sign In',
      forgotPassword: 'Forgot password?',
    },
    setupProfile: {
      heading: 'Set up your profile',
      subheading: 'Tell us about yourself so we can match you with the right rides',
      nameLabel: 'Full name',
      nameHelperText: 'First and last name required',
      nameValidationError: 'Please enter both your first and last name.',
      passwordLabel: 'Password',
      passwordPlaceholder: 'Create a password (min. 6 characters)',
      bioLabel: 'Bio',
      bioPlaceholder: 'Tell others a bit about yourself...',
      paceLabel: 'Preferred pace',
      noPreference: 'No preference',
      submitButton: 'Get Started',
    },
    confirm: {
      expiredLink: 'The invite link may have expired. Please ask your admin for a new invite.',
    },
  },

  dashboard: {
    noRides: 'No upcoming club rides',
    noRidesDescription: 'Check back soon — ride leaders will post new rides here.',
    myRides: {
      emptyTitle: 'No rides on your schedule yet',
      emptyDescription: 'Browse upcoming club rides and sign up for one that fits.',
      emptyCta: 'Browse Rides',
    },
    greeting: {
      morning: 'Good morning',
      afternoon: 'Good afternoon',
      evening: 'Good evening',
      night: 'Welcome back',
    },
    greetingWithName: (greeting: string, name: string) =>
      name ? `${greeting}, ${name}` : greeting,
    actionBar: {
      yourNextRide: 'Your Next Ride',
      nextLedRide: 'Your Next Led Ride',
      waitlistClosed: 'No Spots Opened',
      pendingApprovals: 'Pending Approvals',
      pendingApprovalsCount: (count: number) =>
        `${count} member${count === 1 ? '' : 's'} waiting for approval`,
      ridesNeedingLeader: 'Rides Need a Leader',
      ridesNeedingLeaderCount: (count: number) =>
        `${count} ride${count === 1 ? '' : 's'} this week without a leader`,
      weatherWatch: 'Weather Watch',
      weatherWatchDetail: 'This ride may be affected by weather conditions',
    },
    feed: {
      heading: 'More Club Rides',
    },
    announcementBanner: {
      dismiss: 'Dismiss',
    },
    nudge: {
      heading: 'Next Club Ride',
      browseCta: 'Browse Rides',
      noSignupsTitle: 'No rides on your schedule',
      noSignupsDescription: 'Browse upcoming rides and find one that fits your schedule.',
      noRidesTitle: 'No club rides scheduled yet',
      noRidesDescription: 'Check back soon — ride leaders will post new rides here.',
    },
  },

  rides: {
    feed: {
      heading: 'All Upcoming Club Rides',
      emptyState: {
        title: 'No upcoming club rides',
        description: 'Check back soon — ride leaders will post new rides here.',
      },
    },
    filter: {
      paceLabel: 'Filter by pace',
      clearFilter: 'Clear filter',
      filteredCount: (count: number) => `${count} ride${count !== 1 ? 's' : ''} showing`,
      noResults: {
        title: 'No matching rides',
        description: 'Try adjusting your filters to see more rides.',
      },
    },
    toolbar: {
      homeFeed: (count: number) => `${count} ride${count !== 1 ? 's' : ''} you're signed up for`,
      allRides: (count: number) => `${count} total ride${count !== 1 ? 's' : ''}`,
    },
    card: {
      ledBy: 'Led by',
      drop: 'Drop',
      riding: 'riding',
      riders: 'Riders',
      distance: 'Distance',
      elevation: 'Elevation',
      time: 'Time',
      joinRide: 'Join ride',
      joinWaitlist: 'Join waitlist',
      signedUp: 'Signed up',
      signupSuccess: (rideName: string) => `You're in for ${rideName}`,
      signupDescription: "You'll get a reminder before the ride",
      waitlisted: 'Waitlisted',
      waitlistSuccess: (rideName: string) => `On the waitlist for ${rideName}`,
      waitlistDescription: "We'll notify you if a spot opens up",
      signupError: "Couldn't sign up — try again",
      undone: (rideName: string) => `Removed from ${rideName}`,
      undoneDescription: 'You can rejoin anytime before the ride',
      undo: 'Undo',
      rateLimited: 'Easy there — give it a moment',
      spotsRemaining: (remaining: number) => `${remaining} spots left`,
      moreTags: (count: number) => `+${count}`,
    },
    status: {
      weatherWatch: 'Weather Watch',
      weatherWatchDescription: 'Weather Watch — this ride may be affected by weather conditions.',
      cancelled: 'Cancelled',
      aboutToStart: 'Ride starts soon',
      inProgress: 'Ride in progress',
      completed: 'Completed',
      signupClosed: 'Sign-ups are closed',
    },
    detail: {
      createdBy: (name: string) => `Created by ${name}`,
      signUp: 'Sign Up',
      joinWaitlist: 'Join Waitlist',
      cancelSignUp: 'Cancel Sign-Up',
      spotsRemaining: (remaining: number, total: number) => `${remaining}/${total} spots remaining`,
      spotsFilled: (confirmed: number, capacity: number) => `${confirmed}/${capacity} spots filled`,
      waitlistedCount: (count: number) => `${count} waitlisted`,
      confirmedCount: (count: number) => `${count} confirmed`,
      dropRide: 'Drop ride',
      noDrop: 'No-drop',
      viewRoute: 'View Route',
      viewRouteOn: (serviceName: string) => `View route on ${serviceName}`,
      signedUp: "You're signed up!",
      cancelled: 'This ride has been cancelled',
      cancelledLocked: 'Cancelled rides cannot be edited.',
      signupClosedContact: 'Contact the ride leader to join',
      waitlistClosed: 'Waitlist closed — no spots opened',
      leaveRide: 'Leave',
      cancelConfirmTitle: 'Cancel your sign-up?',
      cancelConfirmDescription:
        'Your spot will be released and the next person on the waitlist will be promoted.',
      cancelConfirmAction: 'Cancel Sign-Up',
      cancelConfirmKeep: 'Keep My Spot',
      distanceLabel: 'Distance',
      elevationLabel: 'Elevation',
      routeMapPlaceholder: 'Route map coming soon',
      goingCount: (total: number) => `${total} going`,
      spotsCount: (confirmed: number, capacity: number | null) =>
        capacity
          ? capacity - confirmed === 0
            ? `${confirmed} riders — Ride full`
            : `${confirmed} riders — ${capacity - confirmed} spots left`
          : `${confirmed} signed up`,
      ridersHeading: (confirmed: number, waitlisted: number, capacity: number | null) => {
        const parts: string[] = [];
        if (capacity != null) {
          parts.push(`${confirmed} confirmed`);
        } else {
          parts.push(`${confirmed} signed up`);
        }
        if (waitlisted > 0) {
          parts.push(`${waitlisted} waitlisted`);
        }
        return `Riders — ${parts.join(' · ')}`;
      },
    },
    actionBar: {
      joinRide: 'Join Ride',
      leaveRide: 'Leave Ride',
      joinWaitlist: 'Join Waitlist',
      leaveWaitlist: 'Leave Waitlist',
      rideFull: 'Ride full',
      cancelled: 'Cancelled',
      completed: 'Completed',
      youreIn: "You're in",
      waitlistPosition: (pos: number) => `Waitlist #${pos}`,
      spotsOf: (confirmed: number, capacity: number | null) =>
        capacity ? `${confirmed} of ${capacity} spots` : `${confirmed} signed up`,
      youreInSpots: (confirmed: number, capacity: number | null) =>
        capacity ? `You're in · ${confirmed} of ${capacity}` : `You're in · ${confirmed} signed up`,
      confirmLeaveTitle: 'Leave this ride?',
      confirmLeave: 'Leave',
      confirmCancel: 'Cancel',
      soleLeaderTitle: "You're the only leader",
      soleLeaderDescription:
        'Every ride needs a leader. Cancel the ride, or add a co-leader first so they can take over.',
      soleLeaderDismiss: 'Never mind',
      soleLeaderCancelRide: 'Cancel Ride',
      soleLeaderAddCoLeader: 'Add Co-Leader',
      soleLeaderConfirmCancelTitle: 'Cancel this ride?',
      soleLeaderConfirmCancelDescription:
        'This ride will be cancelled and removed from the schedule.',
      soleLeaderConfirmCancelWarning: (count: number) =>
        `This will notify ${count === 1 ? '1 rider' : `all ${count} riders`}`,
      soleLeaderConfirmCancel: 'Confirm Cancel',
      editRide: 'Edit',
      cancelRide: 'Cancel Ride',
      cancelRideWarning: (count: number) =>
        `This will notify ${count === 1 ? '1 rider' : `all ${count} riders`}`,
      confirmCancelRide: 'Confirm Cancel',
      cancelRideDialogTitle: 'Cancel this ride?',
      cancelRideDialogDescription: 'This ride will be cancelled and removed from the schedule.',
    },
    create: {
      heading: 'New Ride',
      submitButton: 'Publish Ride',
    },
    recurring: {
      toggle: 'Make this a recurring ride',
      frequency: 'Repeat',
      badge: 'Recurring',
      endCondition: 'Ends',
      endAfter: 'After',
      occurrences: 'Occurrences',
      endOnDate: 'On date',
      endNever: 'Never',
    },
    edit: {
      heading: 'Edit Ride',
      duplicateRide: 'Duplicate Ride',
      recurringPrompt: 'This ride is part of a recurring series.',
      editThisOnly: 'Edit this ride only',
      editAllFuture: 'Edit all future rides',
      cancelRide: 'Cancel This Ride',
      cancelConfirm: (title: string) => `Cancel "${title}"? All signed-up riders will be notified.`,
      cancelReasonLabel: 'Reason (optional)',
      cancelReasonPlaceholder: 'Weather, insufficient signups, etc.',
      confirmCancel: 'Yes, Cancel Ride',
      keepRide: 'Keep Ride',
      signups: 'Signups',
      coLeaders: 'Co-Leaders',
      addCoLeader: 'Add',
      coLeaderPlaceholder: 'Select a leader...',
      coLeaderAdded: 'Co-leader added',
      coLeaderRemoved: 'Co-leader removed',
      noEligibleLeaders: 'No eligible leaders to add.',
    },
    form: {
      // Section headings
      sectionBasics: 'Basics',
      sectionRideDetails: 'Ride Details',
      sectionWhenWhere: 'When & Where',
      sectionRoute: 'Route',
      sectionSettings: 'Settings',
      sectionAdditional: 'Additional',
      sectionRiders: 'Riders',
      sectionCoLeaders: 'Co-Leaders',
      sectionWhen: 'When',
      sectionWhere: 'Start Location',
      sectionRideType: 'Ride Type',
      sectionRouteStats: 'Route Stats',
      sectionDetails: 'Details',
      sectionSchedule: 'Schedule',

      // Step-based headings (progressive disclosure)
      stepRouteHeading: "Let's start with a route",
      stepDetailsHeading: 'Now, tell us about the ride',
      stepWhenWhereHeading: 'When and where does it start?',
      stepAdditionalHeading: 'Any final details?',

      // Import quick-start
      importHeading: 'Start from a route',
      importDescription: 'Import from a connected service to pre-fill ride details.',
      importConfirmed: (routeName: string) => `"${routeName}" imported`,
      importChange: 'Change route',
      viaService: (serviceName: string) => `via ${serviceName}`,
      viaLink: 'via link',
      connectPrompt: 'Connect a service to import routes',

      // URL detection
      fetchRouteDetails: 'Fetch route details',
      fetchingRoute: 'Fetching\u2026',
      fetchRouteError: 'Could not fetch route details.',
      orDivider: 'or',
      pasteRouteLink: 'Paste a route link',
      pasteRoutePlaceholder: 'Paste a link from Strava, RWGPS, Komoot...',
      addRouteButton: 'Add route',
      pasteLinkHelper:
        'Pasted links won\u2019t show a route map. Import from a connected service for a richer rider experience.',
      routeLinkAdded: 'Route link added',
      linkOnlyPreviewLabel: 'This is what riders will see',
      linkOnlyViewRoute: (serviceName: string) => `View route on ${serviceName}`,
      linkOnlyHint: (serviceName: string) =>
        `Riders will see a link to ${serviceName}. Connect your account to show them the route map.`,
      linkOnlyHintGeneric:
        'Riders will see a link to the route. Connect a service to show them the route map.',
      linkOnlyConnect: (serviceName: string) => `Connect ${serviceName}`,
      linkOnlyRemove: 'Remove',

      // Fields
      title: 'Title',
      date: 'Date',
      pickDate: 'Pick a date',
      startTime: 'Start time',
      pickTime: 'Pick a time',
      hour: 'Hour',
      minute: 'Min',
      meetingLocation: 'Location Name',
      locationAddress: 'Address',
      startLocationFromRoute: 'Start location set from route',
      startLocationHint: 'Import a route to auto-detect the start location',
      startLocationManualHint:
        'Connect your account to auto-fill the start location, or enter it manually below',
      startLocationUnavailable: 'Starting location unavailable',
      scrapingRoute: 'Fetching route details\u2026',
      routeRequired: 'A route link is required to create a ride',
      paceGroup: 'Pace Group',
      distance: 'Distance (km)',
      elevation: 'Elevation (m)',
      capacity: 'Capacity',
      coLeaders: 'Co-Leaders',
      coLeadersNoneSelected: 'No co-leaders selected',
      coLeadersCount: (count: number) => `${count} co-leader${count === 1 ? '' : 's'} selected`,
      coLeadersUnavailable: 'Not available \u2014 already leading another ride',
      coLeadersCancelled: 'Not available \u2014 cancelled their signup',
      routeName: 'Route Name',
      routeLink: 'Route Link',
      isDropRide: 'Drop ride',
      description: 'Description',
      selectLocation: 'e.g. Evergreen Brick Works',
      addressPlaceholder: 'e.g. 550 Bayview Ave, Toronto',
      locationPickerHeading: 'Start Location',
      locationPickerSearch: 'Search for a place\u2026',
      locationPickerSavedHeading: 'Saved Locations',
      locationPickerConfirm: 'Confirm Location',
      locationPickerSaveToggle: 'Save to club locations',
      locationPickerMapHint: 'Tap the map to place a pin',
      locationPickerNoSaved: 'No saved locations yet',
      selectPace: 'Select pace...',
      serviceNotConnected: 'Not connected',
      toggleOn: 'On',
      toggleOff: 'Off',
      optional: '(optional)',
      required: 'Title, date, start time, meeting location, pace group, and capacity are required.',
      fieldRequired: 'Required',
      descriptionPlaceholder: 'Brief description of the ride...',
      descriptionHelper: 'A few words help riders know what to expect.',
      addDescription: 'Add a description',
      addCoLeader: 'Add a co-leader',
      replaceRoute: 'Replace this route?',
      replaceRouteDescription: 'Import a new route to replace the current one.',
    },
    roster: {
      noSignups: 'No signups yet.',
      waitlisted: 'Waitlisted',
      leader: 'Leader',
      leaders: 'Leaders',
      riders: 'Riders',
      joined: (timeAgo: string) => `Joined ${timeAgo} ago`,
      removeRider: 'Remove',
      removeConfirmTitle: (name: string) => `Remove ${name} from this ride?`,
      removeConfirmDescription: "They'll be notified and their spot will be released.",
      removeConfirmKeep: 'Keep',
      removeSuccess: (name: string) => `${name} has been removed from this ride.`,
    },
    comments: {
      heading: 'Comments',
      placeholder: 'Write a comment...',
      sendAriaLabel: 'Send comment',
      submit: 'Post',
      edit: 'Edit',
      save: 'Save',
      cancelEdit: 'Cancel',
      delete: 'Delete',
      deleteConfirmTitle: 'Delete comment?',
      deleteConfirm: 'This comment will be permanently removed.',
      deleteFailed: 'Failed to delete comment.',
      edited: '(edited)',
      noComments: 'No comments yet. Be the first!',
    },
    reactions: {
      addReaction: 'Add a reaction',
      reactedBy: (names: string[]) => {
        if (names.length === 0) return '';
        if (names.length === 1) return names[0];
        if (names.length === 2) return `${names[0]} and ${names[1]}`;
        return `${names[0]}, ${names[1]}, and ${names.length - 2} more`;
      },
    },
    importRoute: {
      button: 'Add Route',
      heading: 'Add a Route',
      routesTab: 'Routes',
      activitiesTab: 'Activities',
      modes: {
        strava: {
          heading: 'Strava',
          connected: 'Browse your saved routes and recent rides.',
          notConnected: 'Connect your Strava account to browse routes.',
          connectButton: 'Connect',
        },
        ridewithgps: {
          heading: 'Ride with GPS',
          connected: 'Browse your saved routes and recent trips.',
          notConnected: 'Connect your Ride with GPS account to browse routes.',
          connectButton: 'Connect',
        },
        paste: {
          heading: 'Paste a link',
          description: 'Strava, Ride with GPS, Komoot, or any route URL.',
        },
        gpx: {
          heading: 'GPX file',
          comingSoon: 'Coming soon',
        },
      },
      noConnections: {
        title: 'No services connected',
        description: 'Connect Strava or Ride with GPS from your profile to import routes.',
        connectButton: 'Go to Profile',
      },
      noRoutes: {
        title: 'No routes found',
        description: 'Create routes in Strava or Ride with GPS and they\u2019ll appear here.',
      },
      noActivities: {
        title: 'No ride activities found',
        description: 'Your recent cycling activities will appear here.',
      },
      loadMore: 'Load More',
      loading: 'Loading routes\u2026',
      errorFetch: 'Failed to load routes. Please try again.',
      errorDisconnected: (name: string) =>
        `Your ${name} connection has expired. Please reconnect from your profile.`,
      imported: 'Route imported \u2014 adjust the details and save.',
      searchPlaceholder: 'Search routes\u2026',
      noSearchResults: 'No matching routes',
    },
  },

  calendar: {
    todayButton: 'Today',
    showAllUpcoming: 'Show all upcoming',
    noRidesOnDay: 'No rides scheduled',
    signedUpFilter: 'Signed up',
    weekdays: ['M', 'T', 'W', 'T', 'F', 'S', 'S'] as const,
  },

  schedule: {
    heading: 'My Rides',
    toolbar: {
      upcoming: (count: number) => `${count} upcoming`,
      past: (count: number) => `${count} past ride${count !== 1 ? 's' : ''}`,
    },
    statusFilter: {
      label: 'View',
      ariaLabel: 'Filter schedule by status',
      upcoming: 'Upcoming',
      past: 'Past',
    },
    emptyState: {
      upcoming: {
        title: 'No upcoming rides on your schedule',
        description: 'Browse upcoming club rides and sign up for one that fits.',
        cta: 'Browse Rides',
      },
      past: {
        title: 'No past rides yet',
        description: 'Your completed rides will show up here.',
      },
    },
    status: {
      confirmed: 'Confirmed',
      waitlisted: (position: number) => `Waitlisted — You're ${ordinal(position)} in line`,
      completed: 'Completed',
      cancelled: 'Cancelled',
    },
    actions: {
      cancelSignup: 'Cancel signup',
      leaveWaitlist: 'Leave waitlist',
      getDirections: 'Get directions',
      viewDetails: 'View details',
    },
    signedUpOn: 'Signed up',
  },

  profile: {
    heading: 'Profile',
    signOut: 'Sign Out',
    recentRides: 'Recent Rides',
    recentRidesLimit: 'Last 5',
    noRidesYet: 'No rides yet — sign up for your first one.',
    headlineStat: {
      label: 'club rides',
    },
    editProfile: 'Edit profile',
    saveChanges: 'Save changes',
    saved: 'Profile updated',
    bioPlaceholder: 'Add a short bio',
    noBio: 'No bio yet',
    bioSaved: 'Bio updated',
    paceSaved: 'Pace preference updated',
    sections: {
      about: 'About',
      contact: 'Contact',
      contactInfo: 'Contact information',
      preferences: 'Preferences',
      paceGroup: 'Preferred Pace',
      memberSince: (since: string) => `Member since ${since}`,
      role: 'Role',
      emergencyContact: 'Emergency contact',
    },
    stats: {
      totalRides: 'Total Rides',
      thisMonth: 'This Month',
      distance: 'Distance',
      elevation: 'Elevation',
      delta: (change: number) => `${change > 0 ? '+' : ''}${change} vs last month`,
    },
    statsBento: {
      totalRides: 'Total rides',
      thisMonth: 'This month',
    },
    contactInfo: {
      nameLabel: 'Name',
      phoneLabel: 'Phone',
      emailLabel: 'Email',
      noPhone: 'No phone number set',
      saved: 'Contact info updated',
    },
    personalInfo: {
      heading: 'Personal Information',
      firstNameLabel: 'First Name',
      lastNameLabel: 'Last Name',
      dateOfBirthLabel: 'Date of Birth',
      genderLabel: 'Gender',
      genderOptions: {
        male: 'Male',
        female: 'Female',
      },
      countryLabel: 'Country',
      countryOptions: {
        CA: 'Canada',
        US: 'United States',
      },
      streetAddress1Label: 'Street Address',
      streetAddress2Label: 'Apt / Suite / Unit',
      cityLabel: 'City',
      provinceLabel: 'Province',
      stateLabel: 'State',
      postalCodeLabel: 'Postal Code',
      zipCodeLabel: 'Zip Code',
      notSet: 'Not set',
      postalCodeInvalidError: 'Please enter a valid postal code',
      provinces: {
        AB: 'Alberta',
        BC: 'British Columbia',
        MB: 'Manitoba',
        NB: 'New Brunswick',
        NL: 'Newfoundland and Labrador',
        NS: 'Nova Scotia',
        NT: 'Northwest Territories',
        NU: 'Nunavut',
        ON: 'Ontario',
        PE: 'Prince Edward Island',
        QC: 'Quebec',
        SK: 'Saskatchewan',
        YT: 'Yukon',
      },
      states: {
        AL: 'Alabama',
        AK: 'Alaska',
        AZ: 'Arizona',
        AR: 'Arkansas',
        CA: 'California',
        CO: 'Colorado',
        CT: 'Connecticut',
        DE: 'Delaware',
        FL: 'Florida',
        GA: 'Georgia',
        HI: 'Hawaii',
        ID: 'Idaho',
        IL: 'Illinois',
        IN: 'Indiana',
        IA: 'Iowa',
        KS: 'Kansas',
        KY: 'Kentucky',
        LA: 'Louisiana',
        ME: 'Maine',
        MD: 'Maryland',
        MA: 'Massachusetts',
        MI: 'Michigan',
        MN: 'Minnesota',
        MS: 'Mississippi',
        MO: 'Missouri',
        MT: 'Montana',
        NE: 'Nebraska',
        NV: 'Nevada',
        NH: 'New Hampshire',
        NJ: 'New Jersey',
        NM: 'New Mexico',
        NY: 'New York',
        NC: 'North Carolina',
        ND: 'North Dakota',
        OH: 'Ohio',
        OK: 'Oklahoma',
        OR: 'Oregon',
        PA: 'Pennsylvania',
        RI: 'Rhode Island',
        SC: 'South Carolina',
        SD: 'South Dakota',
        TN: 'Tennessee',
        TX: 'Texas',
        UT: 'Utah',
        VT: 'Vermont',
        VA: 'Virginia',
        WA: 'Washington',
        WV: 'West Virginia',
        WI: 'Wisconsin',
        WY: 'Wyoming',
      },
    },
    membership: {
      heading: 'Membership',
      memberNumberLabel: 'Member Number',
      membershipTypeLabel: 'Membership Type',
      membershipSubtypeLabel: 'Subtype',
      statusLabel: 'Status',
      clubAffiliationsLabel: 'Club Affiliations',
      noMembership: 'No membership on file',
    },
    emergencyContact: {
      nameLabel: 'Emergency Contact Name',
      namePlaceholder: 'Full name',
      phoneLabel: 'Emergency Contact Phone',
      phonePlaceholder: '+1 555-123-4567',
      phonePrefix: '+1',
      phoneInputPlaceholder: '555-123-4567',
      phoneInvalidError: 'Please enter a valid 10-digit phone number',
      relationshipLabel: 'Relationship',
      relationshipPlaceholder: 'e.g. Spouse, Parent, Partner',
      noContact: 'No emergency contact set',
      saved: 'Emergency contact updated',
      visibilityNote: 'Only visible to ride leaders and admins',
      visibilityFootnote:
        'Visible to admins, and to ride leaders within 12 hours of a ride they lead with this rider.',
    },
    emergencyAccess: {
      banner: (rideName: string, expiresTime: string) =>
        `Visible as ride leader for ${rideName} \u00b7 access expires ${expiresTime}`,
    },
    avatar: {
      uploadButton: 'Change Photo',
      uploading: 'Uploading...',
      removeButton: 'Remove Photo',
      removing: 'Removing...',
      removeConfirmTitle: 'Remove profile photo?',
      removeConfirm: "You'll revert to your initials.",
    },
    photoPicker: {
      chooseFromLibrary: 'Choose from library',
      takePhoto: 'Take a photo',
      removePhoto: 'Remove photo',
    },
    publicProfile: {
      deactivated: 'This member is no longer active.',
      contactInfoHeading: 'Contact Information',
      contactInfoNote: 'Visible to admins only',
      emergencyContactNote: 'Visible to ride leaders and admins',
    },
    history: {
      heading: 'Ride History',
      emptyState: {
        title: 'No past rides yet',
        description: 'Your completed rides will show up here.',
      },
      viewAll: 'View all',
    },
    roles: {
      rider: 'Rider',
      ride_leader: 'Ride Leader',
      admin: 'Admin',
    },
  },

  notifications: {
    heading: 'Notifications',
    markAllRead: 'Mark all read',
    badge: {
      ariaLabel: (count: string) => `${count} unread notifications`,
    },
    emptyState: {
      title: 'All caught up',
      description: "You'll see ride updates and announcements here.",
    },
    types: {
      ride_update: 'Ride Update',
      ride_cancelled: 'Ride Cancelled',
      weather_watch: 'Weather Watch',
      signup_confirmed: 'Sign-Up Confirmed',
      waitlist_promoted: 'Waitlist Update',
      waitlist_joined: 'Waitlist Alert',
      announcement: 'Announcement',
      rider_removed: 'Removed from Ride',
      leader_promoted: 'Leader Promoted',
    },
  },

  manage: {
    headingAdmin: 'All Rides',
    headingLeader: 'Your Rides',
    mobileGateTitle: 'This is better on desktop',
    mobileGateDescription:
      'Use the dashboard for quick actions, or switch to desktop for full management tools.',
    leaderHub: {
      heading: 'Your Rides',
      createRide: 'Create a Ride',
      upcomingSection: 'Upcoming',
      pastSection: 'Past Rides',
      statsRidesLed: 'Rides Led',
      statsTotalSignups: 'Total Signups',
      emptyTitle: 'No upcoming rides',
      emptyDescription: 'Create your first ride to get started.',
      spots: (count: number, capacity: number | null) =>
        capacity != null ? `${count}/${capacity}` : `${count}`,
      stats: {
        fillRate: 'Your fill rate',
        cancellationRate: 'Cancellation rate',
        ridesLed: 'Rides led',
        ridesLedContext: (n: number) => `${n} this season`,
        fillRateContext: (change: number) => `${change}% vs. last 30 days`,
        cancellationContext: (count: number) => `${count} this month`,
      },
    },
    clearFilters: 'Clear filters',
    addFilter: 'Add filter',
    rowsPerPage: 'Rows per page',
    paginationOf: 'of',
    sections: {
      rides: 'Rides',
      members: 'Members',
      club: 'Club Settings',
    },
    dashboard: {
      heading: 'Club Dashboard',
      stats: {
        fillRate: 'Rider fill rate',
        cancellationRate: 'Cancellation rate',
        activeMembers: 'Active members',
        newThisMonth: 'New This Month',
        waitlistDemand: 'Waitlisted',
        fillRateContext: (change: number) => `${change}% this month`,
        cancellationContext: (count: number) => `${count} this month`,
        activeMembersContext: (month: string) => month,
      },
      sectionCards: {
        rides: 'Manage rides',
        members: 'Manage members',
        announcements: 'Announcements',
        settings: 'Club settings',
        createRide: 'Create new ride',
        invite: 'Invite new member',
        newAnnouncement: 'Make new announcement',
        edit: 'Edit settings',
        settingsStat: 'Name, branding, preferences',
        upcomingStat: (n: number) => `${n} upcoming ride${n !== 1 ? 's' : ''}`,
        activeStat: (n: number) => `${n} active member${n !== 1 ? 's' : ''}`,
        pendingInvitesStat: (n: number) => `${n} pending invite${n !== 1 ? 's' : ''}`,
        thisWeekStat: (n: number) => `${n} this week`,
      },
      activity: {
        heading: 'Recent Activity',
        empty: 'No recent activity to show.',
        signup: (name: string, ride: string) => `${name} signed up for ${ride}`,
        cancellation: (name: string, ride: string) => `${name} cancelled ${ride}`,
        newMember: (name: string) => `${name} joined the club`,
        signupAction: (ride: string) => `Signed up for ${ride}`,
        cancellationAction: (ride: string) => `Cancelled ${ride}`,
        newMemberAction: 'Joined the club',
      },
    },
    rides: {
      createRide: 'Create Ride',
      all: 'All',
      upcoming: 'Upcoming',
      past: 'Past',
      cancelled: 'Cancelled',
      drafts: 'Drafts',
      toolbar: (count: number) => `${count} ride${count !== 1 ? 's' : ''} managed`,
      noRides: 'No rides to manage. Create your first one!',
      noAllRides: 'No rides',
      noUpcomingRides: 'No upcoming rides',
      noPastRides: 'No past rides',
      noCancelledRides: 'No cancelled rides',
      createdBy: (name: string) => `Created by ${name}`,
      leaderColumn: 'Leader',
      dateColumn: 'Date',
      statusColumn: 'Status',
      actionsColumn: 'Actions',
      searchPlaceholder: 'Search rides...',
      filterStatus: 'Status',
      filterPace: 'Pace Group',
      filterAll: 'All',
    },
    members: {
      heading: 'All Members',
      inviteButton: 'Invite Member',
      totalMembers: (count: number) => `${count} members`,
      roles: {
        rider: 'Rider',
        ride_leader: 'Leader',
        admin: 'Admin',
      },
      you: 'You',
      status: {
        active: 'Active',
        pending: 'Pending',
        inactive: 'Inactive',
      },
      invite: {
        emailLabel: 'Email address',
        emailPlaceholder: 'rider@example.com',
        roleLabel: 'Role',
        sendButton: 'Invite member',
        successTitle: 'Invite created!',
        successMessage: 'Share the invite link below with the new member.',
        inviteAnother: 'Invite Another',
        done: 'Done',
        alreadyInvited: 'This email has already been invited.',
        rateLimited: 'Too many invites sent. Please wait a few minutes and try again.',
      },
    },
    stats: {
      totalRides: 'Total Rides',
      activeMembers: 'Active Members',
      signupsThisWeek: 'Sign-ups This Week',
      avgRiders: 'Avg. Riders/Ride',
    },
    season: {
      heading: 'Season Dates',
      description:
        'Season dates define the window in which ride leaders can schedule rides. Rides outside these dates cannot be created.',
      startLabel: 'Season Start',
      endLabel: 'Season End',
      save: 'Save Season Dates',
      saved: 'Season dates saved',
      noSeason: 'No season dates configured — recurring rides will generate indefinitely.',
    },
    paceTiers: {
      heading: 'Pace Groups',
      description: "Define your club's pace groups. Colors are assigned automatically by position.",
      add: 'Add Tier',
      addButton: 'Add Pace Group',
      nameColumn: 'Name',
      paceRangeColumn: 'Pace Range',
      distanceColumn: 'Distance',
      ridesColumn: 'Rides',
      actionsColumn: 'Actions',
      namePlaceholder: 'Tier name',
      colorLabel: 'Color',
      edit: 'Edit',
      save: 'Save',
      saved: 'Pace tier saved',
      deleted: 'Pace tier deleted',
      delete: 'Delete',
      moveUp: 'Move Up',
      moveDown: 'Move Down',
      restored: 'Pace tier restored',
      undo: 'Undo',
      cannotDelete: 'Cannot delete — rides or templates still use this tier. Reassign them first.',
      duplicateName: 'A pace tier with this name already exists.',
      nameRequired: 'Name is required.',
      movingPace: 'Moving pace',
      typicalDistance: 'Typical distance',
      rangeUnit: 'km/h',
      distanceUnit: 'km',
      paceRange: { min: 10, max: 55, step: 0.5 },
      distanceRange: { min: 10, max: 500, step: 5 },
      upcomingRides: (count: number) => `${count} upcoming ride${count === 1 ? '' : 's'}`,
      cancel: 'Cancel',
      upTo: (max: number, unit: string) => `up to ${max} ${unit}`,
      minPlaceholder: 'min',
      maxPlaceholder: 'max',
    },
    adminMetadata: {
      heading: 'Admin',
      roleLabel: 'Role',
      statusLabel: 'Status',
      notesLabel: 'Admin Notes',
      notesPlaceholder: 'Internal notes about this member...',
      joined: 'Joined',
      lastActive: 'Last Active',
      neverActive: 'Never',
      confirmRoleChange: (name: string, newRole: string) => `Change ${name}'s role to ${newRole}?`,
      confirmRoleDescription: (newRole: string) =>
        newRole === 'ride_leader'
          ? "They'll gain access to ride management tools."
          : newRole === 'admin'
            ? "They'll gain full club management access."
            : "They'll lose management permissions.",
      confirmStatusChange: (name: string, newStatus: string) =>
        `${newStatus === 'inactive' ? 'Deactivate' : 'Reactivate'} ${name}?`,
      confirmStatusDescription: (newStatus: string) =>
        newStatus === 'inactive'
          ? 'They will lose access to the app.'
          : 'They will regain access to the app.',
      roleUpdated: 'Role updated',
      statusUpdated: 'Status updated',
      notesSaved: 'Notes saved',
    },
    memberActions: {
      searchPlaceholder: 'Search members...',
      noMembers: 'No members found.',
      noFilterResults: 'Try adjusting your filters or search.',
      editRole: 'Change Role',
      deactivate: 'Deactivate',
      reactivate: 'Reactivate',
      approve: 'Approve',
      confirmDeactivate: (name: string) => `Deactivate ${name}? They will lose access to the app.`,
      filterAll: 'All',
      filterRiders: 'Riders',
      filterLeaders: 'Leaders',
      filterAdmins: 'Admins',
      filterPending: (count: number) => `Pending (${count})`,
      filterInactive: 'Inactive',
      sortAlpha: 'A–Z',
      sortNewest: 'Newest',
      joinedDate: (date: string) => `Joined ${date}`,
      memberColumn: 'Member',
      roleColumn: 'Role',
      paceGroupColumn: 'Pace Group',
      emailColumn: 'Email',
      phoneColumn: 'Phone',
      ccnColumn: 'CCN #',
      ccnStatusColumn: 'CCN Status',
      joinedColumn: 'Joined',
      statusColumn: 'Status',
      actionsColumn: 'Actions',
    },
    announcements: {
      heading: 'Announcements',
      create: 'Post announcement',
      update: 'Update announcement',
      titleLabel: 'Title',
      titlePlaceholder: 'Announcement title...',
      bodyLabel: 'Message',
      bodyPlaceholder: 'Write your announcement...',
      pin: 'Pin',
      unpin: 'Unpin',
      delete: 'Delete',
      edit: 'Edit',
      noAnnouncements: 'No announcements yet.',
      noFilterResults: 'Try adjusting your search.',
      pinned: 'Pinned',
      pinToTop: 'Pin to top',
      dismissibleLabel: 'Allow members to dismiss',
      typeOptions: {
        general: 'General',
        event: 'Event',
        urgent: 'Urgent',
      },
      searchPlaceholder: 'Search announcements...',
      typeColumn: 'Type',
      titleColumn: 'Title',
      bodyColumn: 'Body',
      dateColumn: 'Published',
      actionsColumn: 'Actions',
    },
    recurringRides: {
      heading: 'Recurring Rides',
      create: 'New Recurring Ride',
      createButton: 'New Template',
      noRecurring: 'No recurring rides set up yet.',
      delete: 'Delete',
      pause: 'Pause',
      resume: 'Resume',
      paused: 'Paused',
      active: 'Active',
      yearRound: 'Year-round',
      generateNow: 'Generate Rides Now',
      dayColumn: 'Day',
      timeColumn: 'Time',
      titleColumn: 'Title',
      paceColumn: 'Pace',
      recurrenceColumn: 'Recurrence',
      seasonColumn: 'Season',
      statusColumn: 'Status',
      actionsColumn: 'Actions',
      filterStatus: 'Status',
      filterDay: 'Day',
      filterAll: 'All',
      searchPlaceholder: 'Search templates...',
      generated: (count: number) => `${count} ride${count === 1 ? '' : 's'} generated`,
      seasonLabel: 'Season',
      seasonStartLabel: 'Season Start',
      seasonEndLabel: 'Season End',
      weeksAheadLabel: 'Generate rides ahead (weeks)',
      recurrence: {
        weekly: 'Weekly',
        biweekly: 'Bi-weekly',
        monthly: 'Monthly',
      },
      dayOfWeek: ['Sunday', 'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday'],
    },
  },

  weather: {
    currentWeather: 'Current Weather',
    feelsLike: (formattedTemp: string) => `Feels like ${formattedTemp}`,
    humidity: (pct: number) => `${pct}% humidity`,
    wind: (speed: number) => `${speed} km/h wind`,
    pop: (pct: number) => `${pct}% chance of rain`,
    stale: 'Weather data may be outdated',
    unavailable: 'Weather unavailable',
    detail: {
      heading: 'Weather Forecast',
      temperature: 'Temperature',
      feelsLike: 'Feels Like',
      wind: 'Wind',
      gusts: 'Gusts',
      precipitation: 'Precipitation',
      humidity: 'Humidity',
      chanceOfRain: 'Chance of Rain',
    },
    severeWarning: 'Severe weather expected — check with your ride leader before heading out.',
    weatherWatchAuto: 'Automatically set due to rain forecast.',
    conditions: {
      clear: 'Clear',
      mostlyClear: 'Mostly Clear',
      partlyCloudy: 'Partly Cloudy',
      overcast: 'Overcast',
      fog: 'Fog',
      drizzle: 'Drizzle',
      rain: 'Rain',
      snow: 'Snow',
      showers: 'Showers',
      snowShowers: 'Snow Showers',
      thunderstorm: 'Thunderstorm',
      unknown: 'Unknown',
    },
  },

  common: {
    decrease: 'Decrease',
    increase: 'Increase',
    loading: 'Loading...',
    error: 'Something went wrong',
    errorDescription: 'An unexpected error occurred. Please try again.',
    retry: 'Try again',
    cancel: 'Cancel',
    discard: 'Discard',
    save: 'Save',
    saved: 'Saved',
    edit: 'Edit',
    done: 'Done',
    back: 'Back',
    notAuthenticated: 'Not authenticated',
    today: 'Today',
    tomorrow: 'Tomorrow',
  },

  errors: {
    accountDeactivated: 'Your account has been deactivated. Please contact your club admin.',
    signInFailed: 'Sign-in failed',
    rideNotFound: 'Ride not found',
    rideCancelled: 'This ride has been cancelled',
    signupClosed: 'Sign-ups are closed for this ride',
    cancellationClosed: 'Cancellation is closed for this ride',
    soleLeaderCannotLeave:
      "You're the only leader of this ride. Cancel the ride instead, or add a co-leader first.",
    createRideFailed: 'Failed to create ride',
    rideDateInPast: 'Ride date cannot be in the past.',
    rideDateOutsideSeason: "Ride date must be within the club's active season.",
    notAuthorized: 'You do not have permission to perform this action',
    cannotDeactivateSelf: 'Cannot deactivate yourself',
    lastAdmin: 'Cannot change role — this is the only admin in the club.',
    noFileProvided: 'No file provided',
    commentEmpty: 'Comment cannot be empty.',
    commentNotFound: 'Comment not found.',
    commentTooLong: (max: number) => `Comment must be ${max} characters or fewer.`,
    alreadyExists: 'Already added.',
    fullNameRequired: 'Full name must include both a first and last name.',
    timeIntervalInvalid: 'Start time must be on a 15-minute interval.',
  },

  notificationMessages: {
    signupConfirmed: {
      title: (rideTitle: string) => `You're signed up for ${rideTitle}`,
    },
    waitlistPromoted: {
      title: (rideTitle: string) => `You're in! Spot opened for ${rideTitle}`,
      body: "A spot opened up and you've been promoted from the waitlist.",
    },
    leaderPromoted: {
      title: (rideTitle: string) => `You're now the lead for ${rideTitle}`,
      body: 'The previous leader left and you have been promoted to primary leader.',
    },
    waitlistJoined: {
      title: (rideTitle: string) => `Waitlist growing for ${rideTitle}`,
      body: 'A rider joined the waitlist. Consider increasing capacity or adding another ride.',
    },
    newRidePosted: {
      title: (rideTitle: string) => `New Ride: ${rideTitle}`,
      body: 'A new ride has been posted. Tap to view details and sign up.',
    },
    rideUpdated: {
      title: (rideTitle: string) => `Ride Updated: ${rideTitle}`,
      body: 'The ride details have been updated. Tap to see changes.',
    },
    rideCancelled: {
      title: (rideTitle: string) => `Ride Cancelled: ${rideTitle}`,
      defaultBody: 'This ride has been cancelled by the organiser.',
    },
    riderRemoved: {
      title: (rideTitle: string) => `Removed from ${rideTitle}`,
      body: 'A ride leader removed you from this ride. Your spot has been released.',
    },
  },
} as const;
